version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node.js version $(node -v)"
      - npm install # 필요한 모듈 설치

  build:
    commands:
      - npm run build # 리액트 애플리케이션 빌드
      - aws s3 cp dist/index.html s3://fronttest-min/index.html
      - aws s3 cp --recursive dist/ s3://fronttest-min/
